### ISSUE TITLE
Remove the use of the deploader.

### ISSUE THREAD

**Issue by covers1624** [AstroDevelopment/Modularity#4]
CCL can now be depended on via the normal mod dependency system. Pease remove the use of the deploader as it has been forced not to download ccl.

**Comment by TheCodedOne** [comment]
The version of modularity on curse forge is not supported and should not be used.

**Comment by covers1624** [comment]
What? That does not solve our issue here. You repack the CCC deploader, it is not needed anymore. get rid of it, CCL can be depended on via the @mod annotation dependencies..

**Comment by TheCodedOne** [comment]
it doesnt even use CCL in the new versions that are yet to be released.
